use anyhow::Result;

use crate::cli::Shell;

const SUBCOMMANDS: &str = "new lint render graph history children ancestors coverage orphans migrate symbols resolve lsp todo start done block reset defer wontdo tree explore completions";

const ID_TAKING: &str =
    "render history children ancestors coverage start done block reset defer wontdo";

pub fn run(shell: Shell) -> Result<()> {
    let script = match shell {
        Shell::Bash => bash_script(),
        Shell::Zsh => zsh_script(),
        Shell::Fish => fish_script(),
    };
    print!("{script}");
    Ok(())
}

fn bash_script() -> String {
    format!(
        r#"# bash completion for `spec` — generated by `spec completions bash`
# Install: source <(spec completions bash)  (or save to /etc/bash_completion.d/spec)
_spec() {{
    local cur prev cmd subcmds id_taking
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    subcmds="{subcmds}"
    id_taking="{ids}"

    # Subcommand position
    if [[ ${{COMP_CWORD}} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$subcmds" -- "$cur") )
        return 0
    fi

    cmd="${{COMP_WORDS[1]}}"

    # Dynamic spec-id completion for id-taking subcommands
    case " $id_taking " in
        *" $cmd "*)
            if [[ "$cur" != -* ]]; then
                local ids
                ids=$(spec __complete ids 2>/dev/null)
                COMPREPLY=( $(compgen -W "$ids" -- "$cur") )
                return 0
            fi
            ;;
    esac
}}
complete -F _spec spec
"#,
        subcmds = SUBCOMMANDS,
        ids = ID_TAKING,
    )
}

fn zsh_script() -> String {
    format!(
        r#"#compdef spec
# zsh completion for `spec` — generated by `spec completions zsh`
# Install: spec completions zsh > ~/.zsh/completions/_spec  (ensure dir is on $fpath)

_spec() {{
    local -a subcmds id_taking
    subcmds=({subcmds})
    id_taking=({ids})

    if (( CURRENT == 2 )); then
        _describe 'spec command' subcmds
        return
    fi

    local cmd="${{words[2]}}"
    if (( ${{id_taking[(I)$cmd]}} )); then
        local -a ids
        ids=("${{(@f)$(spec __complete ids 2>/dev/null)}}")
        _describe 'spec id' ids
    fi
}}
compdef _spec spec
"#,
        subcmds = SUBCOMMANDS,
        ids = ID_TAKING,
    )
}

fn fish_script() -> String {
    let id_cmds = ID_TAKING;
    let mut out = String::new();
    out.push_str("# fish completion for `spec` — generated by `spec completions fish`\n");
    out.push_str("# Install: spec completions fish > ~/.config/fish/completions/spec.fish\n\n");
    out.push_str("function __spec_ids\n    spec __complete ids 2>/dev/null\nend\n\n");
    // Subcommand completions at top level
    let pairs: &[(&str, &str)] = &[
        ("new", "Scaffold a new spec"),
        ("lint", "Run all validation checks"),
        ("render", "Produce render bundles"),
        ("graph", "Emit DOT for the requested graph"),
        ("history", "Regenerate or query commit history"),
        ("children", "List direct refining children"),
        ("ancestors", "List direct refined-by parents"),
        ("coverage", "Clause-by-clause refinement coverage"),
        ("orphans", "List specs with no refinement relationships"),
        ("migrate", "Apply _redirects.toml"),
        ("symbols", "List source symbols through a language server"),
        ("resolve", "Resolve a spec: URL"),
        ("lsp", "Run the forge-spec language server"),
        ("todo", "List open tasks"),
        ("start", "Mark a task as in-progress"),
        ("done", "Mark a task as done"),
        ("block", "Mark a task as blocked"),
        ("reset", "Reset a task to pending"),
        ("defer", "Mark a task as deferred"),
        ("wontdo", "Mark a task as wontdo"),
        ("tree", "Print a tree of all specs"),
        ("explore", "Interactive TUI to browse specs"),
        ("completions", "Print a shell completion script"),
    ];
    for (name, desc) in pairs {
        out.push_str(&format!(
            "complete -c spec -n '__fish_use_subcommand' -a '{name}' -d '{desc}'\n"
        ));
    }
    out.push('\n');
    out.push_str(&format!(
        "complete -c spec -n '__fish_seen_subcommand_from {id_cmds}' -f -a '(__spec_ids)'\n"
    ));
    out
}
